# Set platform to 15.5 to support mobile_scanner and other modern plugins
platform :ios, '15.5'

# CocoaPods analytics sends network stats. Disable it.
# cocoapods_analytics

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Force all pod dependencies to align to iOS 15.5 target
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
